services:
  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: "--data-dir /data --api-key=typesensesearch --enable-cors"
  redis:
    image: redis:latest
    restart: on-failure
    ports:
      - "6379:6379"
    command: ["--save", "60", "1", "--loglevel", "warning"]
  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error_pages:/usr/share/nginx/html
  go_server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - redis
      - typesense
    ports:
      - "8080:8080"
    environment:
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - PORT=8080
      - DATABASE_URL=postgres://yumzies_test_user:yumzies_read_only@yumzies-do-user-17936803-0.l.db.ondigitalocean.com:25060/yumzies
      - SECRET_KEY=hbhbbhscjbhi
      - AccessTokenTTL=86400000
      - RefreshTokenTTL=259200000000
      - TYPESENSE_API_KEY=typesensesearch
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - VIEWS_DIR=./Static/Views
